esphome:
  name: multibridge
  platform: ESP8266
  board: d1_mini
  platformio_options:
    lib_deps: 
      - "rc-switch@2.6.2"
      - "IRremoteESP8266@2.7.1"
      - "ESPAsyncTCP-esphome@1.2.2"
      - "ESPAsyncWebServer-esphome@1.2.6"
  includes:
    - ir.h
# Example configuration entry
sensor:
- platform: custom
  lambda: |-
    auto irSendWrapper = new IRsendWrapper();
    App.register_component(irSendWrapper);
    return {irSendWrapper};
  sensors:
  - name: "tuya_multibridge"


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Multibridge Fallback Hotspot"
    password: !secret ap_password

captive_portal:

# Enable logging
logger:
  esp8266_store_log_strings_in_flash: false

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

# Individual switches
switch:
  - platform: template
    name: tuya demo TV Samsung ON
    icon: "mdi:power-standby"
    optimistic: true
    turn_on_action:
      - lambda: |-
          irsend.sendSAMSUNG(0xE0E040BF, 32, 2);

